version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-confd:/etc/mysql/conf.d
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/WebMedia
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file:
      - ./.env
    environment:
      TZ: Asia/Tokyo
  web:
    build:
      context: ./docker/web
    environment:
      TZ: Asia/Tokyo
    ports:
      - '${PUBLISH_WEB_SERVER_PORT}:80'
    volumes:
      - ./log/nginx:/var/log/nginx
    depends_on:
      - app
    logging:
      options:
        max-size: 10m
        max-file: '10'
volumes:
  mysql-data:
    driver: local